server:
  port: 8888

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  application:
    name: zed-admin
#  jackson:
#    time-zone: GMT+8
#  data:
#    redis:
#      repositories:
#        enabled: false


#  redis:
#    #数据库索引
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    #连接超时时间
#    timeout: 5000


generator:
  enabled: true
  isCover: true


# 文件存储路径
file:
  path: D:\AppleZed\file\
  avatar: D:\AppleZed\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5