##配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apple-zed?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    # Hikari 连接池配置
    hikari:
      pool-name: MyHikariCP
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值:true
      auto-commit: true
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 空闲连接存活最大时间,默认600000（10分钟）
      idle-timeout:
      ## 连接池最大连接数,默认是10
      maximum-pool-size:
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      ## 测试数据库查询语句
      connection-test-query: SELECT 1
      ## 数据库配置信息
      data-source-properties:
        serverTimezone: Asia/Shanghai
        characterEncoding: utf-8
        useUnicode: true
        useSSL: false
        autoReconnect: true
        ## 官方推荐配置
        #### 是否自定义配置，为true时下面两个参数才生效
        cachePrepStmts: true
        #### 连接池大小默认25，官方推荐250-500
        prepStmtCacheSize: 250
        #### 单条语句最大长度默认256，官方推荐2048
        prepStmtCacheSqlLimit: 2048
        #### 新版本MySQL支持服务器端准备，开启能够得到显著性能提升
        useServerPrepStmts: true
        #### 关闭驱动每次请求数据库autocommit,read_only和transaction isolation状态
        useLocalSessionState: true
        #### 批量执行sql(小于3条仍会单条执行)
        rewriteBatchedStatements: true
        #### 缓存结果到元数据
        cacheResultSetMetadata: true
        #### 缓存服务信息配置
        cacheServerConfiguration: true
        #### 使用MySQL高版本,当服务器的状态与Connection.setAutoCommit(boolean)请求的状态不匹配时
        #### 驱动程序是否仅应发出“set autocommit=n”查询
        elideSetAutoCommits: true
        #### 驱动程序是否应维持各种内部定时器,以允许空闲时间计算,以及与服务器的连接失败时允许提供更详细的错误消息？
        #### 将该属性设置为“假”，对于每次查询，至少能减少两次对System.getCurrentTimeMillis()的调用。
        maintainTimeStats: false
        ####  MySQL 8.0 时重启应用,以允许客户端从服务器获取公钥(默认关闭,可能MITM)
        allowPublicKeyRetrieval: true


# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描,多个package用逗号或者分号分隔
  typeAliasesPackage: com.zed.**.entity
  typeEnumsPackage: com.zed.**.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      ## 在 insert 的时候的字段验证策略
      insert-strategy: not_null
      ## 在 update 的时候的字段验证策略
      update-strategy: not_null
      ## 在 select 的时候的字段验证策略
      select-strategy: not_null
      ## 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  # 原生配置(mybatis)
  configuration:
    ## 是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
